version: "3.8"

services:
  mariadb:
    restart: always
    image: "mariadb"
    container_name: "mariadb"
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=blabla
      - MARIADB_DATABASE=ejudge
      - MARIADB_USER=ejudge
      - MARIADB_PASSWORD=blabla
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ejudge_net

  ejudge:
    build:
      context: .
    restart: always
    image: "ejudge:latest"
    container_name: "ejudge"
    ports:
      - "127.0.0.1:8001:80"
    environment:
      - EJUDGE_MYSQL_USER=ejudge
      - EJUDGE_MYSQL_PASSWORD=blabla
      - EJUDGE_MYSQL_DATABASE=ejudge
      - EJUDGE_MYSQL_HOST=mariadb
    volumes:
      - ejudge_data:/home/judges
    depends_on:
      - mariadb
    networks:
      - ejudge_net
    ulimits:
      nofile:
        soft: 1024
        hard: 8192

volumes:
  mysql_data:
    name: mysql_data
  ejudge_data:
    name: ejudge_data
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/ejudge/data/judges
    
networks:
  ejudge_net:
    name: ejudge_net
